# Generated by Django 5.1.13 on 2025-11-05 17:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.EmailField(blank=True, default='cours.ab.carre@gmail.com', help_text='Adresse qui recevra les messages du formulaire. Si vide,on utilisera settings.CONTACT_TO_EMAIL.', max_length=254)),
                ('email_subject', models.CharField(blank=True, default='Nouveau message depuis le formulaire de contact', help_text='Objet du mail envoyé à l’administrateur. Si vide,on utilisera settings.CONTACT_EMAIL_SUBJECT.', max_length=255)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True, help_text='Texte affiché sur la page de remerciement (HTML autorisé).')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
