# Generated by Django 5.0.7 on 2024-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='gdpr_box',
            field=models.BooleanField(default=False),
        ),
    ]
