# Generated by Django 5.1.13 on 2025-11-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_contactpage_gdpr_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='from_address',
            field=models.EmailField(default='no-reply@mon-domaine.com', help_text="Adresse de l'expéditeur. Ne pas mettre une adresse inconnuedu serveur SMTP.", max_length=254),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='subject',
            field=models.CharField(default='Nouveau message depuis le formulaire de contact', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='to_address',
            field=models.EmailField(default='secret-contact-xyz@mon-domaine.com', help_text='Adresse de destination du formulaire.', max_length=254),
        ),
    ]
