# Generated by Django 5.1.13 on 2025-11-03 18:07

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactpage_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='confirmation_message',
            field=wagtail.fields.RichTextField(blank=True, help_text='Texte du mail de confirmation (vous pouvez inclure une formule de politesse). Le message de l’utilisateur sera ajouté automatiquement à la fin.'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='confirmation_subject',
            field=models.CharField(blank=True, default='Merci pour votre message', help_text='Objet de l’email de confirmation envoyé au visiteur.', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='from_address',
            field=models.EmailField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Objet du mail envoyé à l’administrateur. Par défaut : « Nouveau message depuis le formulaire de contact »', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='to_address',
            field=models.EmailField(blank=True, default='contact@mon-domaine.com', help_text='Adresse qui recevra les messages du formulaire. Par défaut : contact@mon-domaine.com', max_length=254),
        ),
    ]
