# Generated by Django 5.0.7 on 2024-07-18 14:37

import wagtail.blocks
import wagtail.fields
import wagtailmarkdown.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='questions',
        ),
        migrations.AddField(
            model_name='homepage',
            name='questions_content',
            field=wagtail.fields.StreamField([('markdown', wagtail.blocks.StreamBlock([('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code'))]))], blank=True, null=True),
        ),
    ]
