# Generated by Django 5.0.7 on 2024-07-19 09:04

import cours_ab_carre.streams.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_questions_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text',
            field=wagtail.fields.StreamField([('text', cours_ab_carre.streams.blocks.RichtextBlock())], blank=True, null=True),
        ),
    ]
