# Generated by Django 5.0.7 on 2024-07-19 14:41

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonials', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Ajouter un titre', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Ajouter un texte', required=True))]))], blank=True, null=True),
        ),
    ]
